name: "Gitleaks Secret Scan"

on:
  push:
    branches: [ "main", "develop", "release/*", "feature/*", "hotfix/*" ]
  pull_request:
    branches: [ "main", "develop", "release/*", "feature/*", "hotfix/*" ]
  workflow_dispatch:

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Важно выкачать всю историю для проверки старых коммитов

      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Если найдет секрет — сборка упадет и пришлет уведомление